name: Build on Branches

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore MkjmPrayerTimes.sln

      - name: Build solution
        run: dotnet build MkjmPrayerTimes.sln --configuration Release --no-restore